---
abstract: 'Expert System with complete algorithms'
author:
  - 'Pablo Fischer (pablo@pablo.com.mx).'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-ExpertSystem-Advanced
no_index:
  directory:
    - examples
    - inc
requires:
  Class::Factory: 1.05
  List::MoreUtils: 0.22
  Moose: 0.87
  YAML::Syck: 1.07
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/pfischer/AI-ExpertSystem-Advanced
version: 0.01
